In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

train_data = pd.read_csv('Predict_Train.csv')
test_data = pd.read_csv('Predict_Test.csv')
riders_data = pd.read_csv('Predict_Riders.csv')

In [2]:
tr_df = train_data.copy()
tr_df1 = tr_df.drop(['Order No', 'User Id', 'Vehicle Type','Personal or Business' ,'Placement - Time', 'Confirmation - Time','Arrival at Pickup - Time', 'Pickup - Time', 'Arrival at Destination - Time', 'Precipitation in millimeters', 'Temperature', 'Rider Id','Pickup Lat','Pickup Long', 'Destination Lat','Destination Long' ,'Arrival at Destination - Weekday (Mo = 1)', 'Arrival at Destination - Day of Month'], axis=1)

In [3]:
tr_df2 = tr_df1.drop(['Placement - Day of Month', 'Placement - Weekday (Mo = 1)', 'Confirmation - Day of Month', 'Confirmation - Weekday (Mo = 1)', 'Arrival at Pickup - Day of Month', 'Arrival at Pickup - Weekday (Mo = 1)'], axis=1)
tr_df2.head()

Platform Type  Pickup - Day of Month  Pickup - Weekday (Mo = 1)  \
0              3                      9                          5   
1              3                     12                          5   
2              3                     30                          2   
3              3                     15                          5   
4              1                     13                          1   

   Distance (KM)  Time from Pickup to Arrival  
0              4                          745  
1             16                         1993  
2              3                          455  
3              9                         1341  
4              9                         1214

In [4]:
pd.get_dummies(tr_df2, columns=['Platform Type', 'Pickup - Day of Month', 'Pickup - Weekday (Mo = 1)'] )
meh = pd.get_dummies(tr_df2, columns=['Platform Type', 'Pickup - Day of Month', 'Pickup - Weekday (Mo = 1)'])
append = meh.iloc[:, :2]
append
before = meh.iloc[:, 2:]
tr_df3 = before.join(append)
tr_df4 = tr_df3.drop(['Platform Type_4', 'Pickup - Day of Month_2', 'Pickup - Weekday (Mo = 1)_7'], axis=1)
tr_df4.head()

Platform Type_1  Platform Type_2  Platform Type_3  Pickup - Day of Month_1  \
0                0                0                1                        0   
1                0                0                1                        0   
2                0                0                1                        0   
3                0                0                1                        0   
4                1                0                0                        0   

   Pickup - Day of Month_3  Pickup - Day of Month_4  Pickup - Day of Month_5  \
0                        0                        0                        0   
1                        0                        0                        0   
2                        0                        0                        0   
3                        0                        0                        0   
4                        0                        0                        0   

   Pickup - Day of Month_6  Pickup - Day of Month_7  Pickup - Day of Month_8  \
0                        0                        0                        0   
1                        0                        0                        0   
2                        0                        0                        0   
3                        0                        0                        0   
4                        0                        0                        0   

   ...  Pickup - Day of Month_30  Pickup - Day of Month_31  \
0  ...                         0                         0   
1  ...                         0                         0   
2  ...                         1                         0   
3  ...                         0                         0   
4  ...                         0                         0   

   Pickup - Weekday (Mo = 1)_1  Pickup - Weekday (Mo = 1)_2  \
0                            0                            0   
1                            0                            0   
2                            0                            1   
3                            0                            0   
4                            1                            0   

   Pickup - Weekday (Mo = 1)_3  Pickup - Weekday (Mo = 1)_4  \
0                            0                            0   
1                            0                            0   
2                            0                            0   
3                            0                            0   
4                            0                            0   

   Pickup - Weekday (Mo = 1)_5  Pickup - Weekday (Mo = 1)_6  Distance (KM)  \
0                            1                            0              4   
1                            1                            0             16   
2                            0                            0              3   
3                            1                            0              9   
4                            0                            0              9   

   Time from Pickup to Arrival  
0                          745  
1                         1993  
2                          455  
3                         1341  
4                         1214  

[5 rows x 41 columns]

In [5]:
ts_df = test_data.copy()
ts_df1 = ts_df.drop(['Order No', 'User Id', 'Vehicle Type','Personal or Business' ,'Placement - Time', 'Confirmation - Time','Arrival at Pickup - Time', 'Pickup - Time', 'Precipitation in millimeters', 'Temperature', 'Rider Id','Pickup Lat','Pickup Long', 'Destination Lat','Destination Long' ], axis=1)
ts_df1['Time from pickup to arrival'] = range(len(ts_df['Platform Type']))
predvar = ts_df1.iloc[:, :-1].values
predvar

array([[ 3, 27,  3, ..., 27,  3,  8],
       [ 3, 17,  5, ..., 17,  5,  5],
       [ 3, 27,  4, ..., 27,  4,  5],
       ...,
       [ 3,  5,  3, ...,  5,  3, 10],
       [ 3, 29,  2, ..., 29,  2, 18],
       [ 3,  4,  2, ...,  4,  2,  8]], dtype=int64)

In [8]:
pd.get_dummies(ts_df2, columns=['Platform Type', 'Pickup - Day of Month', 'Pickup - Weekday (Mo = 1)'] )
meh = pd.get_dummies(ts_df2, columns=['Platform Type', 'Pickup - Day of Month', 'Pickup - Weekday (Mo = 1)'])
append = meh.iloc[:, :2]
append
before = meh.iloc[:, 2:]
ts_df3 = before.join(append)
ts_df4 = ts_df3.drop(['Platform Type_4', 'Pickup - Day of Month_2', 'Pickup - Weekday (Mo = 1)_7'], axis=1)
ts_df4.head()

Platform Type_1  Platform Type_2  Platform Type_3  Pickup - Day of Month_1  \
0                0                0                1                        0   
1                0                0                1                        0   
2                0                0                1                        0   
3                0                0                1                        0   
4                0                0                1                        0   

   Pickup - Day of Month_3  Pickup - Day of Month_4  Pickup - Day of Month_5  \
0                        0                        0                        0   
1                        0                        0                        0   
2                        0                        0                        0   
3                        0                        0                        0   
4                        0                        0                        0   

   Pickup - Day of Month_6  Pickup - Day of Month_7  Pickup - Day of Month_8  \
0                        0                        0                        0   
1                        0                        0                        0   
2                        0                        0                        0   
3                        0                        0                        0   
4                        0                        0                        0   

   ...  Pickup - Day of Month_30  Pickup - Day of Month_31  \
0  ...                         0                         0   
1  ...                         0                         0   
2  ...                         0                         0   
3  ...                         0                         0   
4  ...                         0                         0   

   Pickup - Weekday (Mo = 1)_1  Pickup - Weekday (Mo = 1)_2  \
0                            0                            0   
1                            0                            0   
2                            0                            0   
3                            1                            0   
4                            0                            1   

   Pickup - Weekday (Mo = 1)_3  Pickup - Weekday (Mo = 1)_4  \
0                            1                            0   
1                            0                            0   
2                            0                            1   
3                            0                            0   
4                            0                            0   

   Pickup - Weekday (Mo = 1)_5  Pickup - Weekday (Mo = 1)_6  Distance (KM)  \
0                            0                            0              8   
1                            1                            0              5   
2                            0                            0              5   
3                            0                            0              5   
4                            0                            0              6   

   Time from pickup to arrival  
0                            0  
1                            1  
2                            2  
3                            3  
4                            4  

[5 rows x 41 columns]

In [7]:
ts_df2 = ts_df1.drop(['Placement - Day of Month', 'Placement - Weekday (Mo = 1)', 'Confirmation - Day of Month', 'Confirmation - Weekday (Mo = 1)', 'Arrival at Pickup - Day of Month', 'Arrival at Pickup - Weekday (Mo = 1)'], axis=1)
ts_df2.head()

Platform Type  Pickup - Day of Month  Pickup - Weekday (Mo = 1)  \
0              3                     27                          3   
1              3                     17                          5   
2              3                     27                          4   
3              3                     17                          1   
4              3                     11                          2   

   Distance (KM)  Time from pickup to arrival  
0              8                            0  
1              5                            1  
2              5                            2  
3              5                            3  
4              6                            4

In [9]:
X = tr_df4.iloc[: , :-1].values
y = tr_df4.iloc[: , -1].values
y

array([ 745, 1993,  455, ..., 2953, 1380, 2128], dtype=int64)

In [10]:
predvar = ts_df4.iloc[:, :-1].values
predvar

array([[ 0,  0,  1, ...,  0,  0,  8],
       [ 0,  0,  1, ...,  1,  0,  5],
       [ 0,  0,  1, ...,  0,  0,  5],
       ...,
       [ 0,  0,  1, ...,  0,  0, 10],
       [ 0,  0,  1, ...,  0,  0, 18],
       [ 0,  0,  1, ...,  0,  0,  8]], dtype=int64)

In [11]:
from xgboost import XGBRegressor
mod = XGBRegressor(max_depth=1, random_state=42)
mod.fit(X, y)

[23:29:07] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.


XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, gamma=0,
             importance_type='gain', learning_rate=0.1, max_delta_step=0,
             max_depth=1, min_child_weight=1, missing=None, n_estimators=100,
             n_jobs=1, nthread=None, objective='reg:linear', random_state=42,
             reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
             silent=None, subsample=1, verbosity=1)

In [12]:
b = mod.predict(predvar)
b

array([1490.6624, 1163.1937, 1144.0409, ..., 1648.5328, 2434.1497,
       1509.8152], dtype=float32)

In [13]:
ts_df['Time from pickup to arrival'] = b
newerF = ts_df[['Order No', 'Time from pickup to arrival']]
newerF.to_csv("Submit_1.csv", index=False)
newerF.head()

Order No  Time from pickup to arrival
0  Order_No_19248                  1490.662354
1  Order_No_12736                  1163.193726
2    Order_No_768                  1144.040894
3  Order_No_15332                  1106.962891
4  Order_No_21373                  1282.040405